"""Configuration for preprocessing and rule-discovery utilities."""

from __future__ import annotations

from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
PIC_DIR = PROJECT_ROOT / "pic"
PROJECTED_DIR = PIC_DIR / "projected_tifs"
MERGED_RGB_ENHANCED_DIR = PIC_DIR / "merged_rgb_enhanced"

RULE_DISCOVERY_DIR = PROJECT_ROOT / "rule_discovery"
RULE_TABLES_DIR = RULE_DISCOVERY_DIR / "tables"
RULE_FIGURES_DIR = RULE_DISCOVERY_DIR / "figures"
RULE_OVERLAYS_DIR = RULE_DISCOVERY_DIR / "overlays"
RULE_PATCHES_DIR = RULE_DISCOVERY_DIR / "sampled_patches"
RULES_V2_DIR = RULE_DISCOVERY_DIR / "rules_v2"
RULES_V2_TABLES_DIR = RULES_V2_DIR / "tables"
RULES_V2_OVERLAYS_DIR = RULES_V2_DIR / "overlays"
RULES_V2_SAMPLED_REVIEW_DIR = RULES_V2_DIR / "sampled_review"
RULES_V2_1_DIR = RULE_DISCOVERY_DIR / "rules_v2_1"
RULES_V2_1_TABLES_DIR = RULES_V2_1_DIR / "tables"
RULES_V2_1_OVERLAYS_DIR = RULES_V2_1_DIR / "overlays"
RULES_V2_1_DEBUG_CASES_DIR = RULES_V2_1_DIR / "debug_cases"
RULES_V2_1_SAMPLED_REVIEW_DIR = RULES_V2_1_DIR / "sampled_review"
RULES_V2_3_DIR = RULE_DISCOVERY_DIR / "rules_v2_3"
RULES_V2_3_TABLES_DIR = RULES_V2_3_DIR / "tables"
RULES_V2_3_OVERLAYS_DIR = RULES_V2_3_DIR / "overlays"
RULES_V2_3_DEBUG_CASES_DIR = RULES_V2_3_DIR / "debug_cases"
RULES_V2_3_SAMPLED_REVIEW_DIR = RULES_V2_3_DIR / "sampled_review"
RULES_V2_4_DIR = RULE_DISCOVERY_DIR / "rules_v2_4"
RULES_V2_4_TABLES_DIR = RULES_V2_4_DIR / "tables"
RULES_V2_4_FIGURES_DIR = RULES_V2_4_DIR / "figures"
RULES_V2_4_OVERLAYS_DIR = RULES_V2_4_DIR / "overlays"
RULES_V2_4_SAMPLED_REVIEW_DIR = RULES_V2_4_DIR / "sampled_review"
RULES_V2_3_BOXES_DIR = RULE_DISCOVERY_DIR / "rules_v2_3_boxes"
RULES_V2_3_BOXES_TABLES_DIR = RULES_V2_3_BOXES_DIR / "tables"
RULES_V2_3_BOXES_OVERLAYS_DIR = RULES_V2_3_BOXES_DIR / "overlays"
RULES_V2_3_BOXES_SAMPLED_REVIEW_DIR = RULES_V2_3_BOXES_DIR / "sampled_review"
RULES_V2_BOXES_DIR = RULE_DISCOVERY_DIR / "rules_v2_boxes"
RULES_V2_BOXES_TABLES_DIR = RULES_V2_BOXES_DIR / "tables"
RULES_V2_BOXES_OVERLAYS_DIR = RULES_V2_BOXES_DIR / "overlays"
RULES_V2_BOXES_SAMPLED_REVIEW_DIR = RULES_V2_BOXES_DIR / "sampled_review"

PAIR_DISTANCE_MIN = 6.0
PAIR_DISTANCE_MAX = 48.0
PAIR_LINE_DISTANCE_MAX = 8.0
PAIR_SCORE_PATCH_QUANTILE = 0.90
MAX_PATCHES = 40
PATCH_SIZE = 96
RULES_V2_PATCH_SIZE = 112
PAIR_REQUIRE_MUTUAL_TOP_K = 2
PAIR_IDEAL_DISTANCE_MIN = 18.0
PAIR_IDEAL_DISTANCE_MAX = 35.0
PAIR_MAX_DISTANCE = 45.0
FAR_PAIR_EXTRA_SCORE_REQUIRED = 0.10
USE_EXISTING_SAM_MASKS_FOR_ADJACENCY = True
RUN_SAM_FOR_ADJACENCY_IF_MISSING = False
USE_TRANS_MORPHOLOGY_FALLBACK = True
BUDNECK_LINE_DISTANCE_MAX = 5.0
BUDNECK_PROJECTION_MIN = 0.15
BUDNECK_PROJECTION_MAX = 0.85
BUDNECK_PERPENDICULAR_TOLERANCE_DEG = 35.0
